name: Build RPM and DEB Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev rpm

      - name: Build DEB package
        run: |
          dpkg-deb --build . DEBIAN/
          mv DEBIAN/filescounter-0.1_all.deb .

      - name: Build RPM package
        run: |
          rpmbuild -bb rpmbuild/SPECS/filescounter.spec

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ~filescounter.deb

      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/x86_64/filescounter-1.0-1.x86_64.rpm
