name: Build RPM and DEB Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev rpm

      - name: Build DEB package
        run: |
          dpkg-deb --build . DEBIAN/
      
      - name: Create source tarball
        run: |

      - name: Build RPM package
        run: |
          mkdir -p ~/rpmbuild/SOURCES/ 
          cp rpmbuild/SOURCES/filescounter-0.0.1.tar.gz ~/rpmbuild/SOURCES/
          rpmbuild -bs rpmbuild/SPECS/FilesCounter.spec
          

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: DEBIAN//filescounter_0.1_all.deb

      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: /home/runner/rpmbuild/SRPMS/filescounter-0.0.1-1.src.rpm
